#!/bin/bash

echo "Baixando TST Auto."
wget -O $HOME/.tst/bin/Tst-auto2 https://www.dropbox.com/s/4ov6hyvtxtqgi3p/Tst-auto?dl=0
chmod +x $HOME/.tst/bin/Tst-auto2
echo "TST Auto instalado com sucesso.. digite "Tst-auto --help" no seu terminal para uso do comando"